### ISSUE TITLE
Unable to run configure

### ISSUE THREAD

**Issue by TemplarRiz** [jeffhammond/MOPAC#1]
When i run ./configure in the terminal, it is throwing the error : cannot find f2c or g2c library. Before this there were two line saying : 
checking for main in -lf2c... no
checking for main in -lg2c... no
which was followed by,
configure: error: Cannot find either f2c or g2c library
Should i install f2c separate and copy it here?

**Comment by jeffhammond** [comment]
I merely created a GitHub repo for MOPAC.  For support, please look at http://openmopac.net/.

In this case, please see http://www.netlib.org/f2c/ for the f2c runtime.
